version: '3'

services:
  web:
    image: ghcr.io/dreamgear/portfolio:latest
    container_name: portfolio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`www.dreamgearweb.com`) || Host(`dreamgearweb.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
    networks:
      - proxy-net
    restart: always

networks:
  proxy-net:
    external: true
